### ISSUE TITLE
declared gp inputs 

### ISSUE THREAD

**Issue by yakaracolombia** [HandHeldLegend/HOJA-LIB-ESP32#1]
hi, awesome project but I can't get more than A or B declared, can you help me please

**Comment by mitchellcairns** [comment]
I'll have a fix for this soon @yakaracolombia. Thanks! Bigger problems I'm trying to resolve first ;_;

**Comment by mitchellcairns** [comment]
Almost all inputs are declared with the new push. Still need to declare stick buttons.
