### ISSUE TITLE
No instructions on how to setup.

### ISSUE THREAD

**Issue by chubbybaby31** [HandHeldLegend/HOJA-LIB-ESP32#3]

**Comment by mitchellcairns** [comment]
@chubbybaby31

Please be patient; this project is still a work in progress. Worry not, it's in active development. Currently I'm working on separating the relevant code out to an independent ESP-IDF component so it can be used and make the project folder much cleaner :-)

Thank you,
Mitch

**Comment by mitchellcairns** [comment]
@chubbybaby31 Check out the new commit when you have a chance. The API has been separated into it's own component for easier implementation.

**Comment by mitchellcairns** [comment]
Documentation will be coming very soon. Closing this issue for now.
